### PR TITLE
Fixes for v7

### PR DESCRIPTION
**Pull request by HybridFox**

### CODE REVIEW

**Comment by Kenny167** [comment]
Thanks for the update!

**Review by Kenny167 — APPROVED** [review]

**Comment by Kenny167** [comment]
You'd probably want to change your username:password values for the project   :D
Btw, I keep getting fatal error: invalid login credentials.

**Comment by HybridFox** [comment]
Ofcourse i push with my creds.
No sure about the invalid login creds, i'll give it a look

**Review by Kenny167 — APPROVED** [review]

**Comment by HybridFox** [comment]
After a shit ton of commits (i'm sorry, it's really late), I will now work on a branch for the auto upgrade part.
Btw @Kenny167 is the login issue also happening with other accounts?

**Comment by Kenny167** [comment]
Let me check

**Comment by Kenny167** [comment]
@HybridFox For some reason, it works with a fresh account, but not my main

**Comment by HybridFox** [comment]
Not sure what's up with it then  @Kenny167

**Comment by Kenny167** [comment]
Just tried a password change, but it still doesn't work. Are there any other variables that are required for login? My main account is several years old. Maybe that's the reason?

My main can login to the other python vhack bot, though

**Comment by HybridFox** [comment]
There's the hash, but i'm not if it does anything at all, you'll need to ask @MrSonicMaster Could you also tell me where i can find the password reset?

**Comment by Kenny167** [comment]
Password resets can be accessed through the login window. There is a forgot password option there.

**Comment by Kenny167** [comment]
I've tried everything that I could think of (which isn't much xD) but still haven't gotten it to work. This is so frustrating, considering that it works with a fresh account >.<

**Comment by HybridFox** [comment]
I'm just gonna make some random guesses here: maybe because you're account
is old, it's stored in another way. Any idea how old it is so I can compare
it with my old account?

**Comment by Kenny167** [comment]
@HybridFox It is probably 2-3 years old. 

However, It works with OlympicCode's python bot

**Comment by HybridFox** [comment]
I don't think I have an account that old

**Comment by Kenny167** [comment]
Dammit. Maybe it has to do with the language it's written in?

**Comment by HybridFox** [comment]
Do you mean the language of the game or?

**Comment by Kenny167** [comment]
the bot

**Comment by Kenny167** [comment]
python works fine

**Comment by HybridFox** [comment]
I'm not the original author of the bot though, so I didn't decide what language the bot is in.

**Comment by Kenny167** [comment]
I'm aware of that. i'm just suggesting an answer to the problem.

**Comment by Kenny167** [comment]
Maybe @MrSonicMaster knows a solution?

**Comment by balam1337** [comment]
I can't make the bot work . I do all the change that you make : but when i launch the bot it says :"[i] Initialised with a random delay of 4752.012525640979" And doing nothing after...
Screen of the folders : https://prnt.sc/fw5vtn

**Comment by HybridFox** [comment]
Nothing about logged in @Thesherk ?

**Comment by balam1337** [comment]
The bot start and initialised but doing nothing After that, no error nous message.

**Comment by balam1337** [comment]
Maybe i did wrong the modification that you make

**Comment by HybridFox** [comment]
Might have to do with https://github.com/MrSonicMaster/vHackXT-MoneyBot/issues/12

**Comment by balam1337** [comment]
Oh maybe , i try

**Comment by balam1337** [comment]
I change my password . I't dont contains Caps or number. Still not working . Can you send me the bot in a .rar ?

**Comment by balam1337** [comment]
The bot just do :" [i] Initialised with a random delay of 4508.258353535455 " And nothing after.

**Comment by HybridFox** [comment]
Can you try with a newly created account?

**Comment by balam1337** [comment]
I already try , same thing . Not work.

**Comment by HybridFox** [comment]
Did you get the latest version from my fork?

**Comment by balam1337** [comment]
Yeah , thats why I don't understand , I maybe did something bad. Can you send me your bot in a .rar ?

**Comment by HybridFox** [comment]
Sure, how do I need to send it to you?

**Comment by balam1337** [comment]
Idk , Archive it in .rar. Upload it on sendspace and send the link , it would be very cool. Sory for my english , I'm French.

**Comment by HybridFox** [comment]
I will make sure to do when I'm home

**Comment by balam1337** [comment]
Thx

**Comment by balam1337** [comment]
Can you give the link plz 👍

**Comment by HybridFox** [comment]
I had no time yesterday @Thesherk I will do it today asap

**Comment by HybridFox** [comment]
https://akxis.io/vHackXT-MoneyBot.rar is your link, please also remember to check if your system clock is set correctly, this can cause some errors

**Comment by Kenny167** [comment]
The file you uploaded seems new. Is that your next update? And how do we start the bot without the StartBot_Win.bat?

**Comment by HybridFox** [comment]
Yeah it is, just run `node index.js` in the commandline after you have navigated to the folder where your unpacked files are located
Or you can create a file StartBot_Win.bat and put `node index.js` in it

**Comment by balam1337** [comment]
@HybridFox Trying the bot right now getting error , creating another account to try btw thx for uploading your bot and taking yout time to dev :)

**Comment by balam1337** [comment]
Working now ! Thanks you so much to had taking your times 👍

**Comment by HybridFox** [comment]
No problem, enjoy!

2017-07-18 23:40 GMT+02:00 Thesherk <notifications@github.com>:

**Comment by Kenny167** [comment]
Just to make sure, we edit both index.js and config.json with our credentials?

**Comment by Kenny167** [comment]
When i run the bot, nothing happens.

**Comment by balam1337** [comment]
Auto upgrades and auto money . http://prntscr.com/fxjw8p 👍

**Comment by balam1337** [comment]
Going to put the bot on my raspberry pi and running it 24/24h and 7/7d

**Comment by Kenny167** [comment]
unfortunately, this version still doesn't work with my main.

**Comment by HybridFox** [comment]
What is it (not) doing?

**Comment by balam1337** [comment]
@Kenny167 Have you installed all the modules ?

**Comment by balam1337** [comment]
@HybridFox Do you have a discord ?

**Comment by HybridFox** [comment]
I do now: https://discord.gg/sepht

**Pull request closed without merging**
